; Features and config documentation: https://github.com/Logersnamed/FreecamMod/wiki	

[freecam]
freeze_game = true
freeze_entities = true
freeze_player = true
disable_player_controls = true
reset_camera_state = true

[game_options]
hide_hud = true
disable_anti_aliasing = false
disable_motion_blur = false

[camera_settings]
sensitivity = 1.0
default_speed = 10.0
tilt_speed = 0.5
speed_multiplier = 2.5
zoom_speed = 0.7
min_fov = 0.000087
max_fov = 2.7
pitch_limit = 0.0
invert_camera_x = false
invert_camera_y = false

; smooth_camera_movement - camera won't stop instantly
; smooth_camera_rotation - cinematic camera rotation (like minecraft F8)
; ===========================================
[smooth_camera_settings]
smooth_camera_movement = true
smooth_camera_rotation = false
sensitivity = 1.0
tilt_speed = 0.05

; Unfreeze game for "step" frames. Controlled by step_frames keybind
; ===========================================
[frame_stepper]
step = 1

; Use Ctrl + 0-9 to save camera state
; Use 0-9 to load saved camera state
; Hold multiple keys from 0-9. When all keys are released, interpolation starts in order of press
; ===========================================
[camera_state_manager]
interpolation_time = 3.0

[input]
disable_controller = false
disable_keyboard = false

[features_work_only_in_freecam]
cycle_weather_time = true
speedhack = true

[gui]
show_menu_on_startup = true
enable_notifications = true
notify_freecam = false
notify_speedhack = true
notify_frame_stepped = true
notify_cycle_weather_time = true
notify_record = true
notify_play_record = true
notify_save_state = true
notify_interpolate = true
notify_state_queued = false

; Keybind documentation: https://github.com/Logersnamed/FreecamMod/wiki	
; ===========================================
toggle = F1
toggle_menu = END
reload_config = F5
reset_settings = R + !CTRL
toggle_freeze = P
teleport_to_camera = F3
cycle_weather_time = F4
exit_mod = CTRL + DELETE
start/end_recording = F8
start/end_playing_recording = F9
step_frames = F2
move_forward = W
move_backward = S
move_left = A
move_right = D
move_up = SPACE
move_down = SHIFT
sprint = LBUTTON
zoom_in = 0xBB
zoom_out = 0xBD
tilt_left = Q
tilt_right = E
scroll_zoom_modifier = CTRL
scroll_camera_speed_modifier = !CTRL + !V
scroll_speedhack_modifier = V
toggle_speedhack = F7
reset_speedhack_speed = CTRL + V
timeline_play_pause = SPACE
timeline_add_all_keyframes = O
timeline_delete_selected_keyframes = X
timeline_select_all_keyframes = CTRL + A